// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatBootCommandConfig is an auto-generated flat version of BootCommandConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatBootCommandConfig struct {
	BootGroupInterval *string  `mapstructure:"boot_keygroup_interval" cty:"boot_keygroup_interval" hcl:"boot_keygroup_interval"`
	BootWait          *string  `mapstructure:"boot_wait" cty:"boot_wait" hcl:"boot_wait"`
	BootCommand       []string `mapstructure:"boot_command" cty:"boot_command" hcl:"boot_command"`
	BootKeyInterval   *string  `mapstructure:"boot_key_interval" cty:"boot_key_interval" hcl:"boot_key_interval"`
}

// FlatMapstructure returns a new FlatBootCommandConfig.
// FlatBootCommandConfig is an auto-generated flat version of BootCommandConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*BootCommandConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatBootCommandConfig)
}

// HCL2Spec returns the hcl spec of a BootCommandConfig.
// This spec is used by HCL to read the fields of BootCommandConfig.
// The decoded values from this spec will then be applied to a FlatBootCommandConfig.
func (*FlatBootCommandConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"boot_keygroup_interval": &hcldec.AttrSpec{Name: "boot_keygroup_interval", Type: cty.String, Required: false},
		"boot_wait":              &hcldec.AttrSpec{Name: "boot_wait", Type: cty.String, Required: false},
		"boot_command":           &hcldec.AttrSpec{Name: "boot_command", Type: cty.List(cty.String), Required: false},
		"boot_key_interval":      &hcldec.AttrSpec{Name: "boot_key_interval", Type: cty.String, Required: false},
	}
	return s
}
