// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package common

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatCatalogConfig is an auto-generated flat version of CatalogConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatCatalogConfig struct {
	ISOCatalog        *string `mapstructure:"iso_catalog" cty:"iso_catalog" hcl:"iso_catalog"`
	TempCatalogPrefix *string `mapstructure:"temp_catalog_prefix" cty:"temp_catalog_prefix" hcl:"temp_catalog_prefix"`
	CacheISO          *bool   `mapstructure:"cache_iso" cty:"cache_iso" hcl:"cache_iso"`
	CacheOverwrite    *bool   `mapstructure:"cache_overwrite" cty:"cache_overwrite" hcl:"cache_overwrite"`
}

// FlatMapstructure returns a new FlatCatalogConfig.
// FlatCatalogConfig is an auto-generated flat version of CatalogConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*CatalogConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatCatalogConfig)
}

// HCL2Spec returns the hcl spec of a CatalogConfig.
// This spec is used by HCL to read the fields of CatalogConfig.
// The decoded values from this spec will then be applied to a FlatCatalogConfig.
func (*FlatCatalogConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"iso_catalog":         &hcldec.AttrSpec{Name: "iso_catalog", Type: cty.String, Required: false},
		"temp_catalog_prefix": &hcldec.AttrSpec{Name: "temp_catalog_prefix", Type: cty.String, Required: false},
		"cache_iso":           &hcldec.AttrSpec{Name: "cache_iso", Type: cty.Bool, Required: false},
		"cache_overwrite":     &hcldec.AttrSpec{Name: "cache_overwrite", Type: cty.Bool, Required: false},
	}
	return s
}
